# Generated by Django 4.1.13 on 2025-04-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('б/у', 'б/у'), ('новый', 'новый')], default='б/у', max_length=50),
        ),
    ]
