# Generated by Django 4.1.13 on 2025-04-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-id']},
        ),
    ]
